"""
Models for Galp messages

Not in actual use yet
"""

from typing import Literal, Annotated, TypeVar
from enum import Enum
from pydantic import BaseModel, Field, PlainSerializer

from .lower_protocol import Route
from .task_types import TaskName, TaskDef, CoreTaskDef

def task_key(msg: list[bytes]) -> bytes:
    """
    Generate an identifier for the message
    """
    # Most messages are unique per verb + first arg
    return msg[0] + msg[1]

class Role(str, Enum):
    """
    Enum identifying the role of a peer in the system
    """
    POOL = 'pool'
    WORKER = 'worker'

M = TypeVar('M', bound='BaseMessage')

class BaseMessage(BaseModel):
    """
    Base class for messages
    """
    incoming: Route
    forward: Route
    verb: str

    @classmethod
    def reply(cls: type[M], other: 'BaseMessage', **kwargs) -> M:
        """
        Contruct a message from the given args, extracting and swapping the
        incoming and forward routes from `other`
        """
        return cls(incoming=other.forward, forward=other.incoming, **kwargs)

    @classmethod
    def plain_reply(cls: type[M], route: tuple[Route, Route], **kwargs) -> M:
        """
        Contruct a message from the given args, extracting and swapping the
        incoming and forward routes from a legacy Route tuple.

        TODO: Compat method, to be removed
        """
        incoming, forward = route
        return cls(incoming=forward, forward=incoming, **kwargs)

class Doing(BaseMessage):
    """
    A message signaling that a task has been allocated or started

    Attributes:
        name: the task name
    """
    verb: Literal['doing'] = Field('doing', repr=False)

    name: TaskName

class Done(BaseMessage):
    """
    A message signaling that a task has been succesful run

    Attributes:
        task_def: the task
        children: the child tasks, typically not yet run, generated by the task
            execution
    """
    verb: Literal['done'] = Field('done', repr=False)

    task_def: TaskDef
    children: list[TaskName]

class Exit(BaseMessage):
    """
    A message asking a peer to leave the system
    """
    verb: Literal['exit'] = Field('exit', repr=False)

class Exited(BaseMessage):
    """
    Signals that a peer (unexpectedly) exited. This is typically sent by an
    other peer that detected the kill event

    Attributes:
        peer: the local id (pid) of the exited peer
    """
    verb: Literal['exited'] = Field('exited', repr=False)

    peer: str

class Failed(BaseMessage):
    """
    Signals that the execution of task has failed

    Attributes:
        task_def: the definition of the failed task
    """
    verb: Literal['failed'] = Field('failed', repr=False)

    task_def: CoreTaskDef

class Found(BaseMessage):
    """
    A message notifying that a task was registered, but not yet executed

    Attributes:
        task_def: the task definition
    """
    verb: Literal['found'] = Field('found', repr=False)

    task_def: TaskDef

class Get(BaseMessage):
    """
    A message asking for an already computed resource

    Attributes:
        name: the task name
    """
    verb: Literal['get'] = Field('get', repr=False)

    name: TaskName

class Illegal(BaseMessage):
    """
    A message notifying that a previously sent message was malformed

    Attributes:
        reason: an error message
    """
    verb: Literal['illegal'] = Field('illegal', repr=False)

    reason:str

class NotFound(BaseMessage):
    """
    A message indicating that no trace of a task was found

    Attributes:
        name: the task name
    """
    verb: Literal['notfound'] = Field('notfound', repr=False)

    name: TaskName

class Put(BaseMessage):
    """
    A message sending a serialized task result

    Atrributes:
        name: the task name whose result is sent
        data: the serialized result data
        children: the subordinate task names that are linked from within the
            serialized data
    """

    verb: Literal['put'] = Field('put', repr=False)

    name: TaskName
    data: bytes
    children: list[TaskName]

class Ready(BaseMessage):
    """
    A message advertising a peer joining the system

    Attributes:
        local_id: a string identifying the worker in a local system, typically the pid
        mission: a bytestring identifying why the peer is joining
    """
    verb: Literal['ready'] = Field('ready', repr=False)

    role: Annotated[Role, PlainSerializer(lambda x: x.value)]
    local_id: str
    mission: bytes

class Stat(BaseMessage):
    """
    A message asking if a task is defined or executed

    Attributes:
        name: the task name
    """
    verb: Literal['stat'] = Field('stat', repr=False)

    name: TaskName

class Submit(BaseMessage):
    """
    A message asking for a task to be executed

    Attributes:
        task_def: the task to execute
    """
    verb: Literal['submit'] = Field('submit', repr=False)

    task_def: CoreTaskDef

Message = (
        Doing | Done | Exit | Exited | Failed | Found | Get | Illegal | NotFound
        | Put | Ready | Stat | Submit
        )
