#!/bin/bash
# service script for the dask scheduler

if [ -f 'scripts/local/jobqueue.sh' ]; then
	.  'scripts/local/jobqueue.sh'
else
	echo 'Fatal: please provide a scripts/local/jobqueue.sh wrapper'
	exit 1
fi

case "$1" in
	'start')
		jobqueue_submit scripts/dask_scheduler.sh "scripts/dask afterstart" > build/local/dask.job
		;;
	'afterstart')
		./service start dask_tunnel >&2
		;;
	'status')
		jobqueue_status < build/local/dask.job
		;;
	'stop')
		jobqueue_stop < build/local/dask.job
		;;
esac
