#!/bin/bash -e
# Simple worker

case "$1" in
	'run')
		if [ ! -d var/venv ]; then
			python3 -m venv var/venv
		fi
		. var/venv/bin/activate
		pip install -r requirements/runtime.txt
		python3 -m galp.worker 'ipc://var/worker.sock' 'var/cache'
		;;
esac
